name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        # Fíjate en la ruta: hangman-e2e/e2e
        run: npm install
        working-directory: ./hangman-e2e/e2e

      - name: Ejecutar Cypress (Headless Mode)
        # Aquí también usamos la ruta con subcarpeta
        run: npx cypress run
        working-directory: ./hangman-e2e/e2e