name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Instalamos TODO para que run-p y los scripts funcionen
      - name: Instalar dependencias del Front
        run: npm install
        working-directory: ./hangman-front

      - name: Instalar dependencias de E2E
        run: npm install
        working-directory: ./hangman-e2e/e2e

      # 2. Ejecutar Cypress
      - name: Ejecutar Tests E2E
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./hangman-e2e/e2e
          # Aquí está el truco: le decimos que arranque el front que está afuera
          start: npm start --prefix ../../hangman-front
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 150