name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        # Usamos --no-package-lock para que no se queje si no lo encuentra
        run: npm install
        working-directory: ./hangman-e2e

      - name: Ejecutar Cypress (Headless Mode)
        # npx cypress run es el comando para servidores (sin abrir ventana)
        run: npx cypress run
        working-directory: ./hangman-e2e